insert into user_account (user_id, user_password, nickname, email, memo, created_at, created_by, modified_at, modified_by) values
    ('kurt', 'asdf1234', 'Kurt', 'kurt@kakao.com', 'I am Kurt.', now(), 'kurt', now(), 'kurt')
;
insert into article (user_account_id, title, content, hashtag, created_by, modified_by, created_at, modified_at) values (1, 'Pellentesque viverra pede ac diam.', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Khaki', 'Coreen', 'Mata', '2022-05-09 04:38:44', '2022-02-16 05:23:27');
insert into article (user_account_id, title, content, hashtag, created_by, modified_by, created_at, modified_at) values (1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Puce', 'Mercie', 'Cello', '2021-10-30 12:39:56', '2022-08-20 18:12:30');
insert into article (user_account_id, title, content, hashtag, created_by, modified_by, created_at, modified_at) values (1, 'Nulla tellus.', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Mauv', 'Malinda', 'Lon', '2021-11-14 03:46:23', '2021-12-18 03:39:09');
insert into article (user_account_id, title, content, hashtag, created_by, modified_by, created_at, modified_at) values (1, 'In congue.', 'In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'Maroon', 'Weber', 'Hazel', '2022-06-06 13:59:19', '2021-12-10 11:22:26');
insert into article (user_account_id, title, content, hashtag, created_by, modified_by, created_at, modified_at) values (1, 'Morbi vel lectus in quam fringilla rhoncus.', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Fuscia', 'Tailor', 'Jori', '2021-11-10 08:23:57', '2021-12-22 16:18:28');
insert into article (user_account_id, title, content, hashtag, created_by, modified_by, created_at, modified_at) values (1, 'Duis at velit eu est congue elementum.', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', null, 'Rickey', 'Harlie', '2022-01-01 01:20:31', '2021-12-23 23:59:16');
insert into article (user_account_id, title, content, hashtag, created_by, modified_by, created_at, modified_at) values (1, 'Aenean lectus.', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', null, 'Stevana', 'Jeannette', '2022-05-29 12:10:20', '2021-12-16 15:56:38');
insert into article (user_account_id, title, content, hashtag, created_by, modified_by, created_at, modified_at) values (1, 'Nulla mollis molestie lorem.', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Purple', 'Clo', 'Catina', '2022-07-28 15:04:48', '2022-01-20 10:40:59');
insert into article (user_account_id, title, content, hashtag, created_by, modified_by, created_at, modified_at) values (1, 'In blandit ultrices enim.', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Yellow', 'Starr', 'Olwen', '2022-07-21 21:29:59', '2022-07-09 14:57:25');
insert into article (user_account_id, title, content, hashtag, created_by, modified_by, created_at, modified_at) values (1, 'Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'Crimson', 'Mil', 'Tommie', '2021-11-04 00:50:49', '2022-08-13 22:48:37');
insert into article_comment (article_id, user_account_id, content, created_at, modified_at, created_by, modified_by) values (1, 1, 'In congue. Etiam justo. Etiam pretium iaculis justo.', '2022-02-14 05:42:25', '2022-10-31 17:54:00', 'Susanne', 'Ada');
insert into article_comment (article_id, user_account_id, content, created_at, modified_at, created_by, modified_by) values (1, 1, 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', '2022-01-13 12:23:14', '2022-02-15 05:32:16', 'Arlene', 'Eyde');
insert into article_comment (article_id, user_account_id, content, created_at, modified_at, created_by, modified_by) values (2, 1, 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', '2022-03-17 15:48:29', '2022-03-23 05:09:49', 'Billi', 'Kelsey');
insert into article_comment (article_id, user_account_id, content, created_at, modified_at, created_by, modified_by) values (3, 1, 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.', '2022-03-08 00:28:30', '2022-04-01 19:42:44', 'Karoly', 'Linell');
insert into article_comment (article_id, user_account_id, content, created_at, modified_at, created_by, modified_by) values (4, 1, 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', '2022-09-12 02:04:18', '2021-12-31 15:18:35', 'Clem', 'Alyse');
insert into article_comment (article_id, user_account_id, content, created_at, modified_at, created_by, modified_by) values (5, 1, 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', '2021-11-14 07:22:36', '2022-09-11 23:13:36', 'Almire', 'Cilka');
insert into article_comment (article_id, user_account_id, content, created_at, modified_at, created_by, modified_by) values (6, 1, 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', '2022-11-26 14:46:57', '2022-03-04 15:15:37', 'Elbert', 'Nester');
insert into article_comment (article_id, user_account_id, content, created_at, modified_at, created_by, modified_by) values (7, 1, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2022-09-30 15:47:30', '2022-08-28 18:18:09', 'Briny', 'Barnaby');
insert into article_comment (article_id, user_account_id, content, created_at, modified_at, created_by, modified_by) values (8, 1, 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', '2022-05-23 18:18:39', '2022-10-16 13:35:10', 'Sarge', 'Vivia');
insert into article_comment (article_id, user_account_id, content, created_at, modified_at, created_by, modified_by) values (9, 1, 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', '2022-02-07 23:55:13', '2022-11-23 23:23:12', 'Rodd', 'Wilfrid');
insert into article_comment (article_id, user_account_id, content, created_at, modified_at, created_by, modified_by) values (1, 1, 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.', '2022-06-15 19:34:03', '2022-02-20 15:56:36', 'Rolph', 'Flin');

